# Generated by Django 5.0.1 on 2024-02-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostModel',
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-created_at',)},
        ),
    ]
